In [1]:
import torch 
import torch.nn as nn

In [6]:
# input 
torch.manual_seed(42)
input = torch.tensor([1.0,2.0,3.0])

In [7]:
neuron = nn.Linear(in_features=3,out_features=1)
output = neuron(input)
output

tensor([1.5244], grad_fn=<ViewBackward0>)

In [11]:
# verify 
print(neuron.weight)
print(neuron.bias)

neuron.weight @ input + neuron.bias

Parameter containing:
tensor([[ 0.4414,  0.4792, -0.1353]], requires_grad=True)
Parameter containing:
tensor([0.5304], requires_grad=True)


tensor([1.5244], grad_fn=<AddBackward0>)